server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://buwivrfgwiydiw:3f853b2f55f10531c6db38ac922168da1be0f976216989fb540fd5d9caec0335@ec2-34-233-0-64.compute-1.amazonaws.com:5432/df0pn7ceqoq4n1
    username: buwivrfgwiydiw
    password: 3f853b2f55f10531c6db38ac922168da1be0f976216989fb540fd5d9caec0335
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    genereate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o Santander Dev Week